//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.4
//     from Packages/com.punintended.tools/Runtime/CommandConsole/Input_CommandConsole.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @Input_CommandConsole : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @Input_CommandConsole()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""Input_CommandConsole"",
    ""maps"": [
        {
            ""name"": ""CommandConsole"",
            ""id"": ""f0484b26-87ce-4c8b-b10d-abf43af57af5"",
            ""actions"": [
                {
                    ""name"": ""Accept"",
                    ""type"": ""Button"",
                    ""id"": ""8e59ad06-b6ba-4c36-a2e1-fa4cac512792"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""ff185739-ae85-408d-9d29-3159e08ea7b8"",
                    ""path"": ""<Keyboard>/enter"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Accept"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // CommandConsole
        m_CommandConsole = asset.FindActionMap("CommandConsole", throwIfNotFound: true);
        m_CommandConsole_Accept = m_CommandConsole.FindAction("Accept", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // CommandConsole
    private readonly InputActionMap m_CommandConsole;
    private ICommandConsoleActions m_CommandConsoleActionsCallbackInterface;
    private readonly InputAction m_CommandConsole_Accept;
    public struct CommandConsoleActions
    {
        private @Input_CommandConsole m_Wrapper;
        public CommandConsoleActions(@Input_CommandConsole wrapper) { m_Wrapper = wrapper; }
        public InputAction @Accept => m_Wrapper.m_CommandConsole_Accept;
        public InputActionMap Get() { return m_Wrapper.m_CommandConsole; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(CommandConsoleActions set) { return set.Get(); }
        public void SetCallbacks(ICommandConsoleActions instance)
        {
            if (m_Wrapper.m_CommandConsoleActionsCallbackInterface != null)
            {
                @Accept.started -= m_Wrapper.m_CommandConsoleActionsCallbackInterface.OnAccept;
                @Accept.performed -= m_Wrapper.m_CommandConsoleActionsCallbackInterface.OnAccept;
                @Accept.canceled -= m_Wrapper.m_CommandConsoleActionsCallbackInterface.OnAccept;
            }
            m_Wrapper.m_CommandConsoleActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Accept.started += instance.OnAccept;
                @Accept.performed += instance.OnAccept;
                @Accept.canceled += instance.OnAccept;
            }
        }
    }
    public CommandConsoleActions @CommandConsole => new CommandConsoleActions(this);
    public interface ICommandConsoleActions
    {
        void OnAccept(InputAction.CallbackContext context);
    }
}
